package mylib;

public class Constants {
	public static final String ISCRITTO = "SEI DIVENTATO FRUITORE! ORA POTRAI USUFRUIRE DEI PRESTITI BIBLIOTECARI";
	public static final String NON_ISCRITTO = "NON PUOI DIVENTARE UN FRUITORE PERCHE' HAI MENO DI 18 ANNI";
	public static final String ELENCO_VUOTO = "L'ELENCO E' VUOTO";
	public static final String ISCRIZIONE_SCADUTA = "ISCRIZIONE SCADUTA";
	public static final String ISCRIZIONE_NON_SCADUTA = "ISCRIZIONE NON ANCORA SCADUTA";
	public static final String ISCRIZIONE_ORA = "PUOI RINNOVARE L'ISCRIZIONE ORA";
	public static final String ISCRIZIONE_RINNOVATA = "ISCRIZIONE RINNOVATA";
	public static final String ISCRIZIONE_TERMINI_SCADUTI = "I TERMINI ENTRO CUI POTER RINNOVARE L'ISCRIZIONE SONO CONCLUSI. " +
			                                                "NON SEI PIU' UN FRUITORE DEL NOSTRO SERVIZIO";
	public static final String ISCRIZIONE_RINNOVATA_TRA_POCO = "DEVI ASPETTARE ANCORA QUALCHE MINUTO PER RINNOVARE L'ISCRIZIONE."
																+ " PUOI RINNOVARLA DA QUEST'ORA: ";
	public static final String FRUITORE_GIA_PRESENTE = "SEI GIA PRESENTE NELL'ELENCO FRUITORI.";
}
